### ISSUE TITLE
Native unit test fails on Windows (Unity)

### ISSUE THREAD

**Issue by 20162026** [platformio/platformio-core#4289]
### Configuration

**Operating system**:
windows 10 and windows 11

**PlatformIO Version** (`platformio --version`):

PlatformIO Core, version 6.0.1
PlatformIO Core, version 6.0.2a2

### Description of problem

after updating to 6.0.*, native unit test on windows fails to link `setUp` and `tearDown` ,
tested on 6.0.1 and 6.0.2a2

on linux everything works fine.

#### Steps to Reproduce

0. install windows 
1. copy example
2. run `pio test`

### Actual Results
linker fails
```
> pio test -vvv
Collected 1 tests (test_hello)

Processing test_hello in native environment
------------------------------------------------------------------------------------------------------------------------
Building...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 1 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Unity @ 2.5.2 (License: MIT, Path: C:\Users\EK\TMP\PROJECT\.pio\libdeps\native\Unity)
Building in test mode
g++ -o .pio\build\native\program.exe .pio\build\native\unity_config_build\unity_config.o .pio\build\native\test\test_hello\hello.o -L.pio\build\native -Wl,--start-group .pio\build\native\libe71\libUnity.a -Wl,--end-group
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .pio\build\native\libe71\libUnity.a(unity.o):unity.c:(.text+0x29da): undefined reference to `setUp'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .pio\build\native\libe71\libUnity.a(unity.o):unity.c:(.text+0x29fe): undefined reference to `tearDown'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\native\program.exe] Error 1
Building stage has failed, see errors above. Use `pio test -vvv` option to enable verbose output.
```

### Expected Results
compile and run unit test

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini

[env:native]
    platform = native

```

**Source file to reproduce issue:**
```cpp
#include "unity.h"
#include "stdio.h"


void hello(){
    TEST_FAIL_MESSAGE("HELLO SHOULD FAIL");
}

int main()
{
    UNITY_BEGIN();
    RUN_TEST(hello);
    UNITY_END();
    return 0;
}
```

### Additional info
example project:  [example.zip](https://github.com/platformio/platformio-core/files/8763936/example.zip)

**Comment by ivankravets** [comment]
We switched to the latest Unity testing framework. It requires setUp/tearDown declaration. We added “weak” declarations to keep maximal compatibility with Core 5.0,but they don’t work on Windows and MinGW. 

So, please declare these functions as described in the latest docs.
