### ISSUE TITLE
Builds using atmelsam framework versions 3.9.0 to 3.5.0 fail in PIO Core 6.0.2

### ISSUE THREAD

**Issue by ollie1400** [platformio/platformio-core#4332]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

Microsoft Windows 10 Pro for Workstations
10.0.19043 Build 19043

**PlatformIO Version** (`platformio --version`):

PlatformIO Core, version 6.0.2

### Description of problem

Projects that use `atmelsam` framework versions `3.9.0` to `3.5.0` fail to build in version `6.0.2` of PIO, but build correctly on version `5.1.0`.

This seems to be because
```
from platformio.device.list import list_serial_ports as get_serialports
```
in `util.py` was changed to
```
from platformio.device.list import list_serial_ports as get_serial_ports
```
but `main.py` in `atmelsam@3.6.1` (and others, see `Additional info` below) is looking for 
```
from platformio.util import get_serialports
```

#### Steps to Reproduce

1. Create a project using board `Arduino MKRZERO` and framework `Arduino`
2. Build the project with `pio run`

### Actual Results

Build fails:

```
> pio run

Processing mkrzero (platform: atmelsam@3.6.1; board: mkrzero; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
ImportError: cannot import name 'get_serialports' from 'platformio.util' (C:\Users\Ollie\.platformio\penv\lib\site-packages\platformio\util.py):
  File "C:\Users\Ollie\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 184:
    env.SConscript("$BUILD_SCRIPT")
  File "C:\Users\Ollie\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\Ollie\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\Ollie\.platformio\platforms\atmelsam@3.6.1\builder\main.py", line 23:
    from platformio.util import get_serialports
======================================================================= [FAILED] Took 0.68 seconds =======================================================================
```

### Expected Results

Build should succeed.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mkrzero]
platform = atmelsam@3.6.1
board = mkrzero
framework = arduino

```

**Source file to reproduce issue:**
```
#include <Arduino.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

### Additional info
I have tested a few other framework versions, these all build correctly:
`platform = atmelsam@8.0.0` (currently latest release)
`platform = atmelsam@4.0.0`

These fail:
`platform = atmelsam@3.9.0`
`platform = atmelsam@3.7.0`
`platform = atmelsam@3.6.1`
`platform = atmelsam@3.6.0`
`platform = atmelsam@3.5.0`

Downgrading the PIO core to version `5.1.0` (at least, I haven't tested other PIO core versions) build correctly.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/pull/4333
